# Generated by Django 6.0.2 on 2026-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0002_article_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('excerpt', models.CharField(max_length=400, verbose_name='Accroche (court résumé)')),
                ('contenu', models.TextField(verbose_name="Contenu complet de l'article")),
                ('categorie', models.CharField(choices=[('sensibilisation', 'Sensibilisation'), ('partenariats', 'Partenariats'), ('actions_terrain', 'Actions terrain'), ('formation', 'Formation'), ('reseau', 'Réseau'), ('evenements', 'Événements'), ('decouverte', 'Découverte')], max_length=50, verbose_name='Catégorie')),
                ('tag', models.CharField(choices=[('a_la_une', 'À la une'), ('international', 'International'), ('terrain', 'Terrain'), ('reportage', 'Reportage'), ('evenement', 'Événement'), ('reseau', 'Réseau'), ('formation', 'Formation')], default='terrain', max_length=50, verbose_name='Tag affiché')),
                ('read_time', models.PositiveSmallIntegerField(default=3, verbose_name='Temps de lecture (minutes)')),
                ('date_pub', models.DateField(verbose_name='Date de publication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image')),
                ('en_vedette', models.BooleanField(default=False, verbose_name='Article vedette (à la une)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-date_pub'],
            },
        ),
    ]
